import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { StoreProvider } from "@/redux/StoreProvider";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata = {
  title: "EduHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <StoreProvider>
          <Header />
          <main>{children}</main>
          <Footer/>
        </StoreProvider>
      </body>
    </html>
  );
}
